[project]
name = "drillapi"
version = "0.0.4"
description = "drillapi"
authors = [{name = "SFOE", email = "geoinformation@bfe.admin.ch"}]
readme = "README.md"
requires-python = ">=3.14"
keywords = ["drillapi"]
dependencies = [
  "fastapi",
  "uvicorn",
  "httpx",
  "owslib",
  "slowapi",
  "pydantic_settings",
  "jinja2",
]

[project.optional-dependencies]
dev = [
  "black",
  "pytest",
  "pre-commit",
  "requests",
  "respx",
  "pytest-asyncio",
]

[project.scripts]
drillapi = "drillapi.__main__:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"